name: 'Step Selector para validaciones pre-productivas'
description: 'Unique step to Validate Status'
inputs:
  nolocking:
    description: "Bloqueante=true"
    required: false
    default: "true"
  type:
    description: "Tipo de conjunto de validaciones"
    required: false
    default: "v3"
  qualitygatedata:
    description: "input que queda para datos recibidos de preparativos"
    required: false
    default: ""

#Inputs para Sentinel
  scan_id:
    description: "ScanId para consultar el Quality Gate en la API Sentinel"
    required: false
    default: 1
  sentinel_url:
    description: "URL base de la API de Sentinel (sin trailing slash)"
    required: false
    default: "https://github-integration.andreani.com"

runs:
  using: "composite"
  steps:
    - name: Validate Quality Gates Sentinel
      continue-on-error: ${{ inputs.nolocking == 'true' }}
      uses: infrastructure-services/continuos-deployment@validate-pre-prod-sentinel
      with:
        scan_id: ${{ inputs.scan_id }}
        sentinel_url: ${{ inputs.sentinel_url }}
