name: 'Build and Deploy'
description: 'Unique step to Build and Deploy'
inputs:
  # ACR
  sonar_url:
    description: "Url SonarQube"
    required: true
  sonar_token:
    description: "Token de acceso SonarQube"
    required: true


runs:
  using: "composite"
  steps:
      - run: echo "✅ Success" 
        shell: bash