name: 'Release base'
description: 'realiza el release con el tag de la versión'
inputs:
  github_token:
    description: "Token para descargar el codigo de templates HELM"
    required: true

outputs:
  new-version:
    description: "Version de la imagen"
    value: ${{ steps.version.outputs.new-version }}
runs:
  using: "composite"
  steps:
    - name: Checkout
      uses: actions/checkout@v4
      with:
        fetch-depth: 0

    - name: Get the branch name
      id: branch
      run: echo "BranchName=$(echo ${GITHUB_REF#refs/heads/})" >> $GITHUB_OUTPUT
      shell: bash

    - name: Use the branch name
      id: semanticBranches
      run: | 
        echo "The branch name is ${{ steps.branch.outputs.BranchName }}"
        if [[ ${{ steps.branch.outputs.BranchName }} == "main" ]]; then
          echo "configureBranch=[\"main\"]" >> $GITHUB_OUTPUT
        else
          echo "configureBranch=[\"main\", {\"name\": \"${{ steps.branch.outputs.BranchName }}\", \"prerelease\": \"${{ steps.branch.outputs.BranchName }}\" }]" >> $GITHUB_OUTPUT
        fi
      shell: bash
        
    - name: "Generate Release"
      id: version
      uses: architecture-it/actions@next-version
      with:
        github_token: ${{ inputs.github_token }}
        only_version: 'false'
        branches: ${{ steps.semanticBranches.outputs.configureBranch }}
