name: "Publish to store Android"
description: "Unique step to Publish to store Android"
inputs:
  # App
  appName:
    description: "Nombre de la aplicacion (dentro del proyecto)"
    required: true
  appVersion:
    description: "tag para subir imagen"
    required: true
  environment:
    description: "nombre de environment"
    required: false
    default: ""
  artifact_name:
    description: "nombre del artifact"
    required: false
    default: ""
  isProd:
    description: "flag para saber si es un despliegue productivo"
    required: false
    default: "false"
outputs:
  aplicacion_id:
    description: "aplicacion id"
    value: ${{ steps.setOutputs.outputs.aplicacion_id }}

runs:
  using: "composite"
  steps:
    - run: echo publish to ${{ inputs.environment }}
      shell: bash
      # si el artifact_name is empty, set it to the appName
    - name: Set artifact name
      id: setArtifactName
      run: |
        if [ -z "${{ inputs.artifact_name }}" ]; then
          echo "artifact_name is empty, setting it to appName and environment"
          echo "name=${{ inputs.appName }}-${{ inputs.environment }}" >> $GITHUB_OUTPUT
        else
          echo "artifact_name is provided: ${{ inputs.artifact_name }}"
          echo "name=${{ inputs.artifact_name }}" >> $GITHUB_OUTPUT
        fi
      shell: bash
      
    - name: Checkout
      uses: actions/checkout@v4
      with:
        fetch-depth: 0

    - name: Download artifact
      uses: actions/download-artifact@v4
      with:
        name: ${{ steps.setArtifactName.outputs.name }}
        path: android/app/build/outputs/

    - name: Set Outputs
      id: setOutputs
      shell: bash
      run: |
        echo "aplicacion_id=1" >> $GITHUB_OUTPUT
