name: 'Publish to Appcenter'
description: 'Publish to Appcenter'
inputs:
  # ACR
  appcenter_token:
    description: "appcenter token"
    required: true
runs:
  using: "composite"
  steps:
    - uses: actions/checkout@v4

    - uses: actions/download-artifact@v4
      with:
        name: release.aab
        path: "android/"

    - name: Set up JDK 17
      uses: actions/setup-java@v4
      with:
        distribution: 'microsoft' # See 'Supported distributions' for available options
        java-version: '17'

    - name: Upload artifact to App Center
      uses: wzieba/AppCenter-Github-Action@v1
      with:
        appName: Platform-mobile/test
        token: ${{ inputs.appcenter_token }}
        group: test
        file: android/app-release.aab
        notifyTesters: true
        debug: false