name: 'Image Tag Check'
description: 'Action to check if provided image tag exists for a certain app and project'
inputs:
  # ACR
  REGISTRY_USER:
    description: "user de acr"
    required: true
  REGISTRY_PASS:
    description: "Token de acr"
    required: true
  ACR_FULL_NAME:
    description: "Nombre del acr con azurecr.io"
    required: true

  # App
  appName:
    description: "Nombre de la aplicacion (dentro del proyecto)"
    required: true
  teamProject:
    description: "Nombre del proyecto/equipo"
    required: true
  appVersion:
    description: "tag a buscar"
    required: true

runs:
  using: "composite"
  steps:
      - name: Check tag existence
        shell: bash
        run: |
            tags=$(curl -s -u "${{ inputs.REGISTRY_USER }}:${{ inputs.REGISTRY_PASS }}" "https://${{ inputs.ACR_FULL_NAME }}/v2/${{ inputs.teamProject }}-${{ inputs.appName }}/tags/list" | jq -r '.tags[]')
            found=false
            for tag in $tags; do
              if [ "$tag" = "${{ inputs.appVersion }}" ]; then
                found=true
                break
              fi
            done
            if $found; then
              echo "Se encontr贸 la versi贸n ${{ inputs.appVersion }}"
              exit 0
            else
              echo "No se encontr贸 la versi贸n ${{ inputs.appVersion }}"
              exit 1
            fi   
