name: "Publish to store Android"
description: "Unique step to Publish to store Android"
inputs:
  # App
  appName:
    description: "Nombre de la aplicacion (dentro del proyecto)"
    required: true
  appVersion:
    description: "tag para subir imagen"
    required: true
  environment:
    description: "nombre de environment"
    required: false
    default: ""

outputs:
  aplicacion_id:
    description: "aplicacion id"
    value: ${{ steps.setOutputs.outputs.aplicacion_id }}

runs:
  using: "composite"
  steps:
    - run: echo publish to ${{ inputs.environment }}
      shell: bash

    - name: Checkout
      uses: actions/checkout@v4
      with:
        fetch-depth: 0

    - name: Download artifact
      uses: actions/download-artifact@v4
      with:
        name: ${{ inputs.appName }}-${{ inputs.environment }}
        path: android/app/build/outputs/

    - name: Set Outputs
      id: setOutputs
      shell: bash
      run: |
        echo "aplicacion_id=1" >> $GITHUB_OUTPUT