name: "Build Android"
description: "Unique step to Build Android"
inputs:
  # App
  appName:
    description: "Nombre de la aplicacion (dentro del proyecto)"
    required: true
  appVersion:
    description: "tag para subir imagen"
    required: true
  environment:
    description: "nombre de environment"
    required: false
    default: ""
  # Build React
  matrix_version:
    description: "matrix de pruebas node"
    required: true
  fontawesome_token:
    description: "token de fontawesome"
    required: false
    default: ""
  packages_token:
    description: "token github para autenticarse en packages"
    required: false
    default: ""
  # Build Android
  java_version: 
    description: "version de java para build"
    required: false
    default: "17"
  command:
    description: "comando a ejecutar la build"
    required: false
    default: "./gradlew assembleRelease bundleRelease --no-daemon"
  ANDROID_KEYSTORE_PASSWORD:
    description: "password del keystore"
    required: true
  ANDROID_KEY_ALIAS:
    description: "alias del keystore"
    required: true
  ANDROID_KEYSTORE:
    description: "keystore"
    required: true

outputs:
  name_environment:
    description: "Nombre del environment"
    value: ${{ steps.setOutputs.outputs.environment }}
  artifact_name:
    description: "URL del environment"
    value: ${{ steps.setOutputs.outputs.artifact_name }}

runs:
  using: "composite"
  steps:
    - run: echo Deploy ${{ inputs.environment }}
      shell: bash

    - name: Checkout
      uses: actions/checkout@v4
      with:
        fetch-depth: 0

    - name: Set Outputs
      id: setOutputs
      shell: bash
      run: |
        echo "environment=${{ inputs.environment }}" >> $GITHUB_OUTPUT
        echo "artifact_name=${{ inputs.appName }}-${{ inputs.environment }}" >> $GITHUB_OUTPUT

    - name: Set up JDK
      uses: actions/setup-java@v4
      with:
        distribution: 'microsoft' # See 'Supported distributions' for available options
        java-version: ${{ inputs.java_version }}

    - uses: architecture-it/actions@react-base-library
      with:
        matrix_version: ${{ inputs.matrix_version }}
        # secrets enabled in all organizations
        packages_token: ${{ inputs.packages_token }}
        fontawesome_token: ${{ inputs.fontawesome_token }}

    - name: Cache Gradle Wrapper
      uses: actions/cache@v2
      with:
        path: ~/.gradle/wrapper
        key: ${{ runner.os }}-gradle-wrapper-${{ hashFiles('gradle/wrapper/gradle-wrapper.properties') }}

    - name: Cache Gradle Dependencies
      uses: actions/cache@v2
      with:
        path: ~/.gradle/caches
        key: ${{ runner.os }}-gradle-caches-${{ hashFiles('gradle/wrapper/gradle-wrapper.properties') }}
        restore-keys: |
          ${{ runner.os }}-gradle-caches-

    - name: Bump version
      uses: chkfung/android-version-actions@v1.2.2
      with:
        gradlePath: android/app/build.gradle # or app/build.gradle.kts
        versionName: ${{ inputs.appVersion }}

    - name: Make Gradlew Executable
      run: cd android && chmod +x ./gradlew
      shell: bash

    - name: Build Android Release
      env:
          ENVFILE: .env.${{ inputs.environment }}
      shell: bash
      run: |
        cd android && ${{ inputs.command }}
      
    - run: cd android && ls -la app/build/outputs/apk/release
      shell: bash

    - name: Setup build tool version variable
      shell: bash
      run: |
        BUILD_TOOL_VERSION=$(ls /usr/local/lib/android/sdk/build-tools/ | tail -n 1)
        echo "BUILD_TOOL_VERSION=$BUILD_TOOL_VERSION" >> $GITHUB_ENV
        echo Last build tool version is: $BUILD_TOOL_VERSION

    - name: Sign app APK
      uses: r0adkll/sign-android-release@v1
      id: sign_app
      with:
        releaseDirectory: android/app/build/outputs/apk/release
        signingKeyBase64: ${{ inputs.ANDROID_KEYSTORE }}
        alias: ${{ inputs.ANDROID_KEY_ALIAS }}
        keyStorePassword: ${{ inputs.ANDROID_KEYSTORE_PASSWORD }}
      env:
        BUILD_TOOLS_VERSION: ${{ env.BUILD_TOOL_VERSION }}

    # Upload to Artifact
    - name: Upload Artifact
      uses: actions/upload-artifact@v4
      with:
        name: ${{ steps.setOutputs.outputs.artifact_name }}
        path: ${{steps.sign_app.outputs.signedReleaseFile}}
        
    - name: Sign app APK
      uses: r0adkll/sign-android-release@v1
      id: sign_app_aab
      with:
        releaseDirectory: android/app/build/outputs/bundle/release
        signingKeyBase64: ${{ inputs.ANDROID_KEYSTORE }}
        alias: ${{ inputs.ANDROID_KEY_ALIAS }}
        keyStorePassword: ${{ inputs.ANDROID_KEYSTORE_PASSWORD }}
      env:
        BUILD_TOOLS_VERSION: ${{ env.BUILD_TOOL_VERSION }}

    # Upload to Artifact
    - name: Upload Artifact
      uses: actions/upload-artifact@v4
      with:
        name: ${{ steps.setOutputs.outputs.artifact_name }}.aab
        path: ${{steps.sign_app_aab.outputs.signedReleaseFile}}
