name: 'Security Test'
description: 'Step to run automated security tests'
inputs:
  appName:
    description: "nombre de aplicación"
    required: true
  teamProject:
    description: "nombre de proyecto"
    required: true
  appVersion:
    description: "Versión de la aplicación"
    required: true
  owner:
    descripción: "Organization Name"
    required: true
  repo:
    descripción: "Repository Name"
    required: true
runs:
  using: "composite"
  steps:
      - run: |
          echo "appName: ${{ inputs.appName }}"
          echo "teamProject: ${{ inputs.teamProject }}"
          echo "appVersion: ${{ inputs.appVersion }}"
          echo "owner: ${{ inputs.owner }}"
          echo "repo: ${{ inputs.repo }}"
        shell: bash
      - run: echo "✅ Success" 
        shell: bash